/*
 * generated by Xtext 2.28.0
 */
package org.xtext.lua.validation;

/**
 * This class contains custom validation rules.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class LuaValidator extends AbstractLuaValidator {

//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					LuaPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}

}
