/*
 * generated by Xtext 2.34.0
 */
package org.xtext.lua52;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.xtext.lua52.converters.LuaValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Lua52RuntimeModule extends AbstractLua52RuntimeModule {
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return LuaValueConverterService.class;
    }
}
