/*
 * generated by Xtext 2.34.0
 */
package org.xtext.lua52;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Lua52StandaloneSetup extends Lua52StandaloneSetupGenerated {

	public static void doSetup() {
		new Lua52StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
