/*
 * generated by Xtext 2.34.0
 */
package org.xtext.lua52.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Lua52UiModule extends AbstractLua52UiModule {

	public Lua52UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
