/*
 * generated by Xtext 2.28.0
 */
package org.xtext.lua.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.lua.lua.Chunk

@ExtendWith(InjectionExtension)
@InjectWith(LuaInjectorProvider)
class LuaParsingTest {
	@Inject
	ParseHelper<Chunk> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			num = 666
			local function foo()
				print("foo bar")
				num = num + 1
			end
			
			foo()
			
			eq = num == 667
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
