/*
 * generated by Xtext 2.34.0
 */
package org.xtext.lua52.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.lua52.Lua52RuntimeModule;
import org.xtext.lua52.Lua52StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Lua52IdeSetup extends Lua52StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Lua52RuntimeModule(), new Lua52IdeModule()));
	}
	
}
