grammar org.xtext.lua.Lua 
	hidden(WS, COMMENT)
	
import 'http://www.eclipse.org/emf/2002/Ecore' as ecore	
generate lua "http://www.xtext.org/lua/Lua"


/**
 * ## Overview ##
 * Grammar is based on the reference grammar given at https://www.lua.org/manual/5.2/manual.html#9 "9 – The Complete Syntax of Lua"
 * and based on the previous Xtext implementation of the Lua 5.1 grammar.
 * 
 * ## Code-styling guidelines ##
 *  - | are used in front of each alternative for easier debugging (can comment the line without having to also comment the |)
 * 
 * 
 * ## Extensible grammars for each Lua version: ##
 * Initially, the idea was to create a new xText grammar for Lua5.2, extending the Lua5.1 grammar.
 * Unfortunately, the AssignmentOrFunctionCall Production rule prevents the extension in a sensible way, since large parts of this grammar (Lua5.1)
 * would need to be duplicated in the extension (see https://github.com/eclipse/xtext/issues/2593).
 * 
 * Should this issue be resolved in the future, the extension can be created as explained here: https://stackoverflow.com/questions/16442508/including-a-grammar-into-another-grammar.
 * The extension grammar could then contain something along the lines of the following:
 * 
   @Override 
	Stat:
		super |
    	{Goto} 'goto' label=LUA_NAME |
		{Label} '::' label=LUA_NAME '::'
	; 
	//[...]
 */

//************** Known Limitations/TODOs **************//
// TODO: currently, something like a=10r30 is possible ("r30" is detected as a functioncall directly after the last right-side-expression of an assignment), not sure how to fix
// TODO: add typing?  https://dslmeinte.wordpress.com/2012/08/03/polymorphic-dispatch-in-xtend/
// TODO: Lua allows for a special comment at the beginning of a script that starts with #. This is currently not supported by this grammar (only special comments starting with #! are supported)
//************************************************//

Chunk:
	//TODO: SPECIAL_COMMENT (#!) is defined as first line starting with #, not #! in Lua reference
	SPECIAL_COMMENT?
	block=Block
;


Block: 
	{Block} (stats+=Stat (=>';')?)* (lastStat=LastStat (=>';')?)? 
;

/**
 * We need to define actions here to differentiate between e.g. different loops:
 * E.g.: If Stat contains the alternatives
    'while' condition=Exp 'do' block=Block 'end' |
    'repeat' block=Block 'until' condition=Exp
 * without actions (i.e. {WhileLoop}, {RepeatLoop}) the serialization would create a while-loop when the original contained a repeat-loop.
 */
Stat returns Stat:
	{EmptyStat} ';'
	| AssignmentOrFunctionCall // Assignment and function call of reference grammar are joined in one rule to allow for disambiguation
	| Label
	| Break // TODO: test, this was initially overlooked when implementing the grammar
    | Goto
    | {DoEndBlock} 'do' block=Block 'end'
    | {WhileLoop} 'while' condition=Exp 'do' block=Block 'end'
    | {RepeatLoop}'repeat' block=Block 'until' condition=Exp
    | {IfThenElse} 'if' condition=Exp 'then' thenBlock=Block (elseIfs+=ElseIf)* ('else' elseBlock=Block)? 'end'
    | NumericFor
    | GenericFor
    | FunctionDeclaration
    | LocalFunctionDeclaration
    | LocalAssignment 
;

LastStat: 
	Return
;

Return:
	{Return} 'return' (expList=ExpList)?
;

/**
 * Explanation for AssignmentOrFunctionCall rule:
 * Previously, we had something like this (as a result from removing left-recursion and ambiguities from the reference grammar):
 		Stat:
 			FunctionCall |
 			Assignment 
 		;
 		
		Assignment:
			varList=VarList '=' expList=ExpList
		;              //    ^ this is the '=' that needs to be reached to differentiate between a PrefixExp matching a Var and a PrefixExp matching a FunctionCall.
		
		VarList returns VarList:
			vars+=Var (',' vars+=Var)*
		;
		* 
		FunctionCall: 
			PrefixExp
		;
		* 
		Var returns Var: 
		    PrefixExp
		;
 * We need to differentiate between a FunctionCall and an Assignment, since the xTexts/ANTLRs lookahead is not able to reach the '=' to do so.
 * Ref. for the fix: https://dslmeinte.wordpress.com/2014/09/11/ambiguitiy-in-xtext-grammars-part-2/
 * 
 * Assignments contain a list of vars and an ExpList, this is used in the linking phase to distinguish
 * cross-references from PrefixExps (right-hand side of an Assignment, inside ExpList i.e. ExpList is parent/container) from declarations
 * (left-hand side of an Assignment, ExpList is NOT parent/container).
 * 
 * Unfortunately, this leads to all PrefixExp being sub-types of Stat.
 */
AssignmentOrFunctionCall returns Stat:
	PrefixExp (
		({FunctionCallStat.prefix=current})
	   	| ({Assignment.vars+=current} (',' vars+=PrefixExp)* =>'=' expList=ExpList)
	)
;

Label:
	{Label} '::' name=LUA_NAME '::'
;

Break:
	{Break} 'break'
;

Goto:
	{Goto} 'goto' ref=[Label|LUA_NAME]
;

ElseIf:
	'elseif' condition=Exp 'then' block=Block
;

NumericFor returns BlockWrapperWithArgs:
	{NumericFor} 'for' arg=Arg '=' fromExp=Exp ',' toExp=Exp (',' stepExp=Exp)? 'do' block=Block 'end'
;

GenericFor returns BlockWrapperWithArgs:
	{GenericFor} 'for' argList=ArgList 'in' expList=ExpList 'do' block=Block 'end'
;

FunctionDeclaration:
	{FunctionDeclaration} 'function' name=FuncName body=FuncBody
;

LocalFunctionDeclaration:
	{LocalFunctionDeclaration} 'local' 'function' name=LUA_NAME body=FuncBody 
;

LocalAssignment:
	{LocalAssignment} 'local' vars=NameList ('=' expList=ExpList)?
;

ExpList: 
	 exps+=Exp ( =>',' exps+=Exp)*
;


//**** Expressions ****//

Exp:
	ExpOr
;
 
// Or: left associative, priority 0
ExpOr returns Exp:
	ExpAnd ('or' {ExpOr.left=current} right=ExpAnd)*
;

// And: left associative, priority 1
ExpAnd returns Exp:
	ExpCompare ('and' {ExpAnd.left=current} right=ExpCompare)*;

// Comparisons: left associative, priority 2
ExpCompare returns Exp:
	ExpConcat (('>' {ExpGt.left=current} right=ExpConcat)
	| ('>=' {ExpGeq.left=current} right=ExpConcat)
	| ('<' {ExpLt.left=current} right=ExpConcat)
	| ('<=' {ExpLeq.left=current} right=ExpConcat)
	| ('==' {ExpEq.left=current} right=ExpConcat)
	| ('~=' {ExpNeq.left=current} right=ExpConcat))*;

// Concatenation: right associative, priority 3
ExpConcat returns Exp:
	ExpAddSub ('..' {ExpConcat.left=current} right=ExpConcat)?;

// addition/subtraction: left associative, priority 4
ExpAddSub returns Exp:
	ExpMultDivMod (('+' {ExpAdd.left=current} right=ExpMultDivMod)
	| ('-' {ExpSub.left=current} right=ExpMultDivMod))*;

// multiplication/division, left associative, priority 5
ExpMultDivMod returns Exp:
	ExpUnary (('*' {ExpMult.left=current} right=ExpUnary)
	| ('/' {ExpDiv.left=current} right=ExpUnary)
	| ('%' {ExpMod.left=current} right=ExpUnary))*;

// Unary operators: right associative, priority 6
ExpUnary returns Exp:
	ExpExponentiation
	| ('not' {ExpNegate} exp=ExpUnary)
	| ('#' {ExpLength} exp=ExpUnary)
	| ('-' {ExpInvert} exp=ExpUnary);

// exponentiation: right associative, priority 7
ExpExponentiation returns Exp:
	ExpPrimary ('^' {ExpExponentiation.left=current} right=ExpUnary)?
;
 
ExpPrimary returns Exp:
	ExpTerminal
	| ExpLiteral
	| ExpVarArgs
	| ExpFunctionDeclaration
	| PrefixExp
	| TableConstructor
	// exp binop exp | unop exp from the reference are handled without left-recursion and describing operator precedences by Exp starting with ExpOr
;

ExpTerminal:
	{ExpNil} 'nil'
	| {ExpFalse} 'false'
	| {ExpTrue} 'true' 
;

ExpLiteral:
	{ExpNumberLiteral} value=NUMBER_LITERAL
	| {ExpStringLiteral} value=LUA_STRING 
;

ExpVarArgs:
	{ExpVarArgs} '...' 
;

// **** Prefix/suffixExp **** //
/**
 * Prefixexp, functioncall and var rules from the reference are joined in this grammar, resulting in so called Features and FeaturePaths.
 * Variable names, table accesses, function calls and expressions may be combined in Lua for accesses and assignments, resulting in FeaturePaths, e.g.
 * var = table.member.func().
 * Features are described by synthetic rules at the end of this grammar, as super-types of Prefix and SuffixExps.
 */

/**
 * "Root" of a FeaturePath, either a Var or a GroupedExp.
 */
PrefixExp:
	 Var
	 | {GroupedExp} '(' exp=Exp ')' =>suffixExp=SuffixExp?
;

Var:
	{Var} name=LUA_NAME =>suffixExp=SuffixExp?
;

/**
 * Continuation of a FeaturePath.
 */
SuffixExp:
	FunctionCall // from FunctionCall in reference, should never be leaf of a path (never on lhs of Assignment)
	| MethodCall // from FunctionCall in reference
	| TableAccess // from Var in reference
	| MemberAccess // from Var in reference
;

FunctionCall:
	({FunctionCall} args=Args =>suffixExp=SuffixExp?)
;

MethodCall:
	 (':' {MethodCall} name=LUA_NAME args=Args =>suffixExp=SuffixExp?)
;

TableAccess:
	 ( '[' {TableAccess} indexExp=Exp ']' =>suffixExp=SuffixExp?)
;

MemberAccess:
	('.' {MemberAccess} name=LUA_NAME =>suffixExp=SuffixExp?)
;

Args: 
	{ParamArgs} '(' (params=ExpList)? ')'
	| TableConstructor
	| {LiteralStringArg} str=LUA_STRING 
;

TableConstructor:
	{TableConstructor} '{' (fieldList=FieldList)? '}'
;

FieldList:
	fields+=Field (=>(','|';') fields+=Field)* (=>(','|';'))? 
;

Field:
	{IndexExpField} '[' indexExp=Exp ']' '=' valueExp=Exp
	| {NameField} name=LUA_NAME '=' valueExp=Exp
	| {ExpField} valueExp=Exp
;

FuncName:
	LUA_NAME ('.' LUA_NAME)* (':' LUA_NAME)?
;

NameList: 
	names+=LocalVar (',' names+=LocalVar)*
;

LocalVar:
	{LocalVar} name=LUA_NAME
;

ExpFunctionDeclaration:
	{ExpFunctionDeclaration} 'function' body=FuncBody
;

FuncBody:
	'(' (parList=ParList)? ')' block=Block 'end'
;

ParList:
	argsList=ArgList (',' varArgs=ExpVarArgs)?
	| ExpVarArgs
;

Arg:
	{Arg} name = LUA_NAME
;

ArgList: 
	args+=Arg (',' args+=Arg)*
;


// **** Synthetic rules **** //
/**
 * The synthetic rules are used to create super-types that are used in the java classes handling the later parsing steps (e.g. linking, scoping).
 */

/*
 * We use the synthetic rule Feature for rules that may define some kind of access on a variable/table as part of a feature path. 
 * They may have a prefix and/or a suffix, e.g. a.member["tableAccess"].
 */
Feature:
	PrefixExp
	| SuffixExp
;

NamedFeature: 
	Var
	| MethodCall // should never be leaf of a path (never on lhs of Assignment)
	| TableAccess // TableAccess has a "name" attribute which is set to the contained expression (indexExp), if the expression is resolvable
	| MemberAccess
;

/*
 * We use the synthetic rule Referenceable to implement cross-references in this grammar. Any model object that can be referenced is a Referenceable with the
 * attribute "name", that can be used during linking to resolve the reference.
 * Many objects/rules are Referenceable and Referencing at the same time, which means they need a "name" attribute (to be Referenceable) AND a "ref" cross-reference
 * (to trigger linking in later parsing phases). Since "name" and "ref" are defined through the same token (i.e. a variable called "var" would have the name "var" and would reference "var"),
 * we cannot set both attribute and cross-reference in the respective rules (at least as far as I understand Xtext grammars).
 * E.g.: In the following code snippet
  		var = {1,2,3}
  		a = var[0]
 * the "var" in the second assignment is a Referenceable (referenced by "a") and a Referencing (referencing the "var" in the first assignment) at the same time.
 */
Referenceable:
	name=LUA_NAME
	| NamedFeature
	| FunctionDeclaration
	| LocalFunctionDeclaration
	| Exp
	| Label
	| Arg
	| LocalVar
	| Field
;

/**
 * Synthetic rule for all rules that contain a cross-reference, i.e. reference some other model object (Referenceable).
 */
Referencing:
	ref=[Referenceable|LUA_NAME]
	| NamedFeature
	| LocalVar
	| Field
	| Goto
;


BlockWrapperWithArgs:
	NumericFor
	| GenericFor
	| FuncBody
;

// **** TERMINALS **** //

// Identifiers can be any string of letters, digits, and underscores, but mustn't begin with a digit.
terminal LUA_NAME returns ecore::EString:
	('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*
;

// Literal Strings can be defined between single or double quotes. They can also be defined using a long format enclosed by long brackets.
// https://www.lua.org/manual/5.1/manual.html#2.1 ("2.1 – Lexical Conventions")
// E.g. [[...]], [=[...]=]
terminal LUA_STRING:
	'"' ('\\' . | !('\\' | '"'))* '"'
	| "'" ('\\' . | !('\\' | "'"))* "'"  
	| LUA_STRING_LONG
;

/* TODO: this is a workaround, long strings should be implemented for an arbitrary number of equals-signs. Attempt below failed. */
terminal LUA_STRING_LONG:
	'[[' -> ']]' 
	| '[=[' -> ']=]'
	| '[==[' -> ']==]'
	| '[===[' -> ']===]'
	| '[====[' -> ']====]'
	| '[=====[' -> ']=====]'
	| '[======[' -> ']======]'
	| '[=======[' -> ']=======]' 
;

// Attempt to implement long strings for arbitrary number of equal signs:
/*
terminal LUA_STRING_LONG:
	'[' LUA_STRING_LONG_CONTENT ']'
;

terminal LUA_STRING_LONG_CONTENT:
	//'[' -> ']' |
	'=' LUA_STRING_LONG_CONTENT '='
	| '[' (.)* ']'
;
*/

/**
 *  From https://www.lua.org/manual/5.1/manual.html#2.1:
 * 
 * "A comment starts with a double hyphen (--) anywhere outside a string. If the text immediately after -- is not an opening long bracket, 
 * the comment is a short comment, which runs until the end of the line. Otherwise, it is a long comment, which runs until the corresponding 
 * closing long bracket. Long comments are frequently used to disable code temporarily."
 * 
 * This implies just one '[' suffices to start a multiline comment, but it seems two are needed.
 */
terminal COMMENT:
	ML_COMMENT | SL_COMMENT
;

terminal ML_COMMENT:
	'--' LUA_STRING_LONG
;
 
terminal fragment MATCH_UNTIL_LINE_BREAK:
	!('\n'|'\r')* ('\r'? '\n')?
;

terminal SL_COMMENT:
	'--' !'[' MATCH_UNTIL_LINE_BREAK
	| '--[' !('['|'=') MATCH_UNTIL_LINE_BREAK
	| '--[=' !('['|'=') MATCH_UNTIL_LINE_BREAK
	| '--[==' !('['|'=') MATCH_UNTIL_LINE_BREAK
	| '--[===' !('['|'=') MATCH_UNTIL_LINE_BREAK
	| '--[====' !('['|'=') MATCH_UNTIL_LINE_BREAK
	| '--[=====' !('['|'=') MATCH_UNTIL_LINE_BREAK
	| '--[======' !('['|'=') MATCH_UNTIL_LINE_BREAK
	| '--[=======' !('['|'=') MATCH_UNTIL_LINE_BREAK 	
;

terminal NUMBER_LITERAL returns ecore::EDouble:
	// rules for double values
	(
		('0'..'9')+ | //Int rule
		('0'..'9')+ '.' ('0'..'9')* | // real rule with int part
		'.' ('0'..'9')+ // real with only decimal places
	)
	(('e'|'E') ('+'|'-')? ('0'..'9')+)? // exponent part 
	
	// rules for hex values
	| HEX_LITERAL
;

// hex rules differ from Lua 5.1 (allow uppercase 'X' and 'A'..'F', fractional part and exponent part)
terminal HEX_LITERAL returns ecore::EDouble:
	( ('0x' | '0X') 
		(
			('0'..'9' | 'a'..'f' | 'A'..'F')+ | //Int rule
			('0'..'9' | 'a'..'f' | 'A'..'F')+ '.' ('0'..'9' | 'a'..'f' | 'A'..'F')* | // real rule with int part
			'.' ('0'..'9' | 'a'..'f' | 'A'..'F')+ // real with only decimal places
		)
	) (('p'| 'P') ('+'|'-')? ('0'..'9')+)? // the exponent part, should be binary per definition but here we just allow any int
;

// Consume all white space, tabs and new line characters
terminal WS:
	(' ' | '\t' | '\r' | '\n')+
; 

terminal SPECIAL_COMMENT:
	('#!' -> ('\n' | '\r'))
;

