package org.xtext.lua;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.resource.XtextResourceSet;
import org.xtext.lua.mocking.MockObjectCreator;
import org.xtext.lua.scoping.LuaGlobalScopeProvider;

/**
 * {@link XtextResourceSet} implementation representing the Lua Code Model. Implements methods to return only the serialisable
 * Resources, given that implicit imports e.g. are not serialisable.
 * @author jsaenz
 *
 */
public class LuaCodeModel extends XtextResourceSet {
		
	/**
	 * {@inheritDoc}
	 * <p>
	 * Note that for this {@link LuaCodeModel} this includes non-serializable resources, e.g. synthetic resources created to contain
	 * mock objects as well as the resources corresponding to implicit imports (Lua libraries).
	 * Use {@link #getOriginalResources()} to get a list of the serializable resources.
	 * </p>
	 * @return the complete {@link ResourceSet} that represents this <code>LuaCodeModel</code>.
	 */
	@Override
	public EList<Resource> getResources() {
		return super.getResources();
	}
	
	/**
	 * Returns all resources contained in this model which are not automatically generated by the
	 * {@link LuaParser}, i.e. all {@link Resource}s that are not implicit (part of the Lua library)
	 * or created as containers for mocked objects. Only the {@link Resource}s returned by this
	 * method can be serialized by the {@link LuaParser}.
	 * <p>
	 * For example, when generating a {@link LuaCodeModel} by parsing a project's directory,
	 * only the {@link Resource}s created from the files in that directory will be returned.
	 * </p>
	 * @return
	 */
	public Collection<Resource> getSerializableResources() {
		return super.getResources().stream()
				.filter(this::isSerializable)
				.toList();
	}
	
	private boolean isSerializable(Resource r) {
		return !(LuaGlobalScopeProvider.isImplicitResource(r) 
				|| r.getURI().equals(MockObjectCreator.MOCKED_RESOURCE_URI));
	}

}
