/*
 * generated by Xtext 2.28.0
 */
package org.xtext.lua;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LuaStandaloneSetup extends LuaStandaloneSetupGenerated {

    public static void doSetup() {
        new LuaStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
