/*
 * generated by Xtext 2.34.0
 */
package org.xtext.lua.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LuaUiModule extends AbstractLuaUiModule {

	public LuaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
