/*
 * generated by Xtext 2.28.0
 */
package org.xtext.lua.ui

import org.eclipse.ui.plugin.AbstractUIPlugin

/** 
 * Use this class to register components to be used within the Eclipse IDE.
 */
class LuaUiModule extends AbstractLuaUiModule {
	new(AbstractUIPlugin plugin) {
		super(plugin)
	}
}
